// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:c63bc297-37a3-4713-83f3-bad6dc87f51c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_OEyQ7sJ8l",
    "aws_user_pools_web_client_id": "4dfl25snf8h3pkcmsdtn11phgo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https:7k4rildyrnhdvaaie662fe2k3i.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "paetzundpartnerweb9354bec955244b78aab125970c0808fc-paetzlife",
    "aws_user_files_s3_bucket_region": "eu-central-1",
    "aws_content_delivery_bucket": "paetzundpartnerweb-20191106183248-hostingbucket-paetzlife",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http:paetzundpartnerweb-20191106183248-hostingbucket-paetzlife.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;

